services:
  be-khana:
    build: .
    ports:
      - target: 8080
        published: 8080
    depends_on:
      - db-khana
    networks:
      - back-tier
      - front-tier
    environment:
        - POSTGRES_URL=jdbc:postgresql://db-khana:5432/db_khana
    secrets:
      - pg-user
      - pg-password

  db-khana:
    image: 'postgres:13-alpine3.20'
    ports:
      - target: 5432
        published: 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - back-tier
    environment:
      - POSTGRES_DB=db_khana
      - POSTGRES_USER_FILE=/run/secrets/pg-user
      - POSTGRES_PASSWORD_FILE=/run/secrets/pg-password
    secrets:
      - pg-user
      - pg-password

volumes:
  pgdata:

networks:
  front-tier:
  back-tier:
#    internal: true # Enable in production

secrets:
  pg-user:
    file: secrets/pg-user.txt
  pg-password:
    file: secrets/pg-password.txt
